### ISSUE TITLE
Secure user logs

### ISSUE THREAD

**Issue by DGKSK8LIFE** [matt-mekha/game-matchmaking-test#6]

**Comment by matt-mekha** [comment]
not sure what this one means

**Comment by DGKSK8LIFE** [comment]
> not sure what this one means

meaning when you're storing logged data, that you do so securely by implementing encryption or whatever else

**Comment by matt-mekha** [comment]
relatively unimportant

**Comment by DGKSK8LIFE** [comment]
doesn't justify closing it
